# Generated by Django 6.0.6 on 2026-06-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intrutor',
            fields=[
                ('id', models.IntegerField(help_text='informe o ID do Instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Informe RG do Instrutor', max_length=15)),
                ('nome', models.CharField(help_text='Informe nome do Instrutor', max_length=70)),
                ('dataNascimento', models.DateField(help_text='Informe Data de nascimento do instrutor')),
                ('telefone', models.CharField(help_text='Informe numero de telefone', max_length=9)),
                ('ddd', models.CharField(help_text='Informe o numero do DDD', max_length=3, null=True)),
                ('codigoTitulo', models.IntegerField(help_text='Informe código título')),
            ],
        ),
    ]
