# Generated by Django 6.0.6 on 2026-06-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0003_alter_instrutor_codigotitulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrutor',
            old_name='codigoTitulo',
            new_name='codigo_Titulo',
        ),
    ]
