# Generated by Django 6.0.6 on 2026-06-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0004_rename_codigotitulo_instrutor_codigo_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrutor',
            old_name='codigo_Titulo',
            new_name='codigo_titulo',
        ),
    ]
