# Generated by Django 6.0.6 on 2026-06-11 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0005_rename_codigo_titulo_instrutor_codigo_titulo'),
        ('titulo', '0002_alter_titulo_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrutor',
            old_name='dataNascimento',
            new_name='data_nascimento',
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='codigo_titulo',
            field=models.ForeignKey(blank=True, db_column='codigo_titulo', help_text='Informe código título do instrutor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulo', to='titulo.titulo'),
        ),
    ]
