# Generated by Django 6.0.6 on 2026-06-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0007_alter_instrutor_codigo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='codigo_titulo',
            field=models.IntegerField(blank=True, help_text='Informe código título do instrutor', null=True),
        ),
    ]
