# Generated by Django 6.0.6 on 2026-06-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipodeatividade',
            fields=[
                ('codigo', models.AutoField(help_text='Código do Tipos de Atividade', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descricao do Tipos de Atividade', max_length=70)),
            ],
        ),
    ]
