# Generated by Django 6.0.6 on 2026-06-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Código da matricula', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome', max_length=70)),
                ('data_inicial', models.DateField(help_text='Informe a data')),
                ('data_final', models.DateField(help_text='Informe a data', null=True)),
            ],
        ),
    ]
