# Generated by Django 6.0.6 on 2026-06-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Informe o numero da turma ', primary_key=True, serialize=False)),
                ('horarioAula', models.IntegerField(help_text='Informar horario da aula')),
                ('duracaoAula', models.IntegerField(help_text='Informar duracao aula')),
                ('dataInicial', models.DateField(help_text='Informe a data inicial da aula')),
                ('dataFinal', models.DateField(help_text='Informe Data Final', null=True)),
                ('codigoTipoAtividade', models.IntegerField(help_text='Informe Tipo de Atividade')),
                ('matriculaMonitor', models.IntegerField(help_text='Informe matricula monitor')),
                ('idInstrutor', models.IntegerField(help_text='Informe ID do Instrutor')),
            ],
        ),
    ]
